### ISSUE TITLE
isVerified() has gone protected

### ISSUE THREAD

**Issue by whitnelson** [jrean/laravel-user-verification#11]
Using a previous version of this package worked great, especially when I wanted a finer grain control over what the user can see on a given page. I would use isVerified to switch things on and off, but that method has gone private for some reason, breaking my implementation. Why is that? Is there a workaround so I can call **UserVerification::isVerified($USER)** again?

Here is the error:

> FatalErrorException in Facade.php line 218:
> Call to protected method Jrean\UserVerification\UserVerification::isVerified() from context 'Illuminate\Support\Facades\Facade

I've confirmed this by simply making isVerfied() a public method.

**Comment by jrean** [comment]
@whitnelson thank you for you comment, `the method has gone protected because I reckon it should be part of the public API — the main purpose of this package is not to allow one check if a user is verified or not.

To do so you may perform the check on your side by doing a simple `if ($user->verified == true) {}` ; `$user` should be an instance of your user and so has a `verified` property.

Does that solve your issue?

Thxs

**Comment by whitnelson** [comment]
This absolutely solves my issue. Thanks so much! And great work!
