### ISSUE TITLE
missing email_verified_at field in migrations

### ISSUE THREAD

**Issue by beniaminorossini** [jrean/laravel-user-verification#194]
On confirmation link click we get
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email_verified_at' in 'field list' (SQL: update `users` set `verification_token` = , `verified` = 1, `email_verified_at` = 2018-11-13 10:24:11 where `email` = info@info.com)`

Seems migrations lack of email_verified_at field.

**Comment by FreekU** [comment]
I experienced the same issue, it seems to be related to the email verification built into 5.7. I resolved it by adding the corresponding column:
`$table->timestamp('email_verified_at')->nullable();`

Source: https://github.com/laravel/laravel/blob/master/database/migrations/2014_10_12_000000_create_users_table.php

**Comment by jrean** [comment]
Hi,

Yeah, as mentioned by @FreekU the last release of the package for Laravel 5.7 introduced the leverage  of the "built-in" `email_verified_at` column from Laravel...
So you need to have/include this column, otherwise you'll get this exception.

I'll do some refactor soon to improve this behaviour.

@FreekU what do you mention about "duplicating some information in the database"?

Thxs
